### ISSUE TITLE
rake db:migrate failed (LoadError: cannot load such file -- sinatra/activerecord/rake)

### ISSUE THREAD

**Issue by jerrychong25** [udacity/galeria#6]
In Windows, I am trying to run `rake db:migrate` as mentioned in Lesson 2 Step 7, but it will prompts following error:
```
D:\GitHub\WebApp\Back End\GaleriaFunctions>rake db:migrate
rake aborted!
LoadError: cannot load such file -- sinatra/activerecord/rake
D:/GitHub/WebApp/Back End/GaleriaFunctions/Rakefile:2:in `<top (required)>'
(See full trace by running task with --trace)
```

Could advise any solution for this error?

Thanks.

**Comment by pabmor** [comment]
Same error here!

**Comment by jerrychong25** [comment]
@pabmor Have you found any solution for this error?

**Comment by pabmor** [comment]
I don't really remember how that ended, sorry.

**Comment by jerrychong25** [comment]
Since no one found solution for this, I will close this issue.
